project: 
  type: book
  output-dir: docs

book:
  title: "Find Biased Features"
  author: "jac-thom"
  date: "Aug. 5, 2024"
  chapters:
    - index.qmd
    - spatialLIBD.qmd
    - mbv_slide.qmd
    - mbv_subject.qmd
    - to_explore.qmd

format:
  html:
    theme: default
